import './examples/basicTypes.ts'
import './examples/interface.ts'
import './examples/symbol.ts'
import './examples/function.ts'
import './examples/generices.ts'
import './examples/class.js'
import './examples/classTs.ts'
import './examples/enum.ts'
